apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: k8s-challenge
  name: k8s-challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-challenge
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: k8s-challenge
    spec:
      containers:
      - image: k8s-challenge:1.0.0
        name: k8s-challenge
        resources: {}
        ports:
          - containerPort: 4000
        env:
          - name: name
            valueFrom:
              configMapKeyRef:
                name: k8s-challenge-cm
                key: name
status: {}
